[[main]]
    identifier = 'home'
    name = 'Home'
    pre = 'ğŸ '
    pageRef = '/'
    weight = 10
[[main]]
    identifier = 'about'
    name = 'About'
    pre = 'ğŸ‘©'
    pageRef = '/about/'
    weight = 20