[[main]]
    identifier = 'home'
    name = 'Home'
    pre = 'ğŸ '
    pageRef = '/'
    weight = 10
[[main]]
    identifier = 'about'
    name = 'About'
    pre = 'ğŸ‘©'
    pageRef = '/about/'
    weight = 20
[[main]]
    identifier = 'projects'
    name = 'Projects'
    pre = 'âœ'
    pageRef = '/projects/'
    weight = 30
[[main]]
    identifier = 'compositions'
    name = 'Compositions'
    pre = 'ğŸ¼'
    pageRef = '/compositions/'
    weight = 40
[[main]]
    identifier = 'contact'
    name = 'Contact'
    pre = 'âœ‰'
    pageRef = '/contact/'
    weight = 100